baseURL: "https://profile.gurusabarish.tech"
languageCode: "en-us"
title: "Ali Amiri portfolio"
theme: "./.."
relativeURLs: true


googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  description: "Ali Amiri - Sofware Developer, Freelancer"

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Ali Amiri"
  profession: "Developer"
  github: "https://github.com/aliamiri"
  linkedin: "https://linkedin.com/in/aliamiriakh"

  # About
  disable_about: false
  descripe_l1_person: "I’m a self-motivated, creative programmer with about ten years of programming and management experience, specializing in java with a keen interest in problem-solving. Although I was away from the academic environment, I’ve always kept the fire alive in my heart by solving math-related problems and reading about various subjects, so I decided to continue my education and currently in the last year of my major in AI at the Sharif University of Technology."
  descripe_l2_person: "I'm always open for new ideas so don't hesitate to contact me"
  skills:
    - name: Back End
      percentage: 90
    - name: Dev-Ops
      percentage: 70
    - name: Front End
      percentage: 60
    - name: Machine Learnings
      percentage: 70

  # Experience
  disable_experience: false
  experience:
    - company: "Google"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Software developer"
      startdate: Feb 2021
      enddate: present
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Facebook"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Mar 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Amazon"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Feb 2019
      enddate: Jan 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.

  # Education
  disable_education: false
  education:
    - degree: "M.S."
      branch: "Artificial Intelligence"
      university: "Sharif University of Technology"
      startedyear: "2019"
      graduation: "2022"
    - degree: "B.S"
      branch: "Information Technology"
      university: "University of Tehran"
      startedyear: "2007"
      graduation: "2014"

  # Projects
  disable_projects: true
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Mathematics Olympiad
      description: Bronze Badge in Iranian Mathematics Olympiad
      img: /images/bronze.png
    - title: Master Enterance Program
      description: Rank 4 in master entrance compatition among 30000 participants 
      img: /images/konkoor.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "aliamiri68@gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: false

  # Blog
  showdescription: false
  tweet: fasle
