baseURL: "https://profile.gurusabarish.tech"
languageCode: "en-us"
title: "Ali Amiri portfolio"
theme: "./.."
relativeURLs: true


googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  description: "Ali Amiri - Sofware Developer, Freelancer"

  # home
  disable_home: false
  profile_image: "/images/profile.jpg"
  name: "Ali Amiri"
  profession: "Developer"
  github: "https://github.com/aliamiri"
  linkedin: "https://linkedin.com/in/aliamiriakh"

  # About
  disable_about: false
  descripe_l1_person: "I’m a self-motivated, creative programmer with about ten years of programming and management experience, specializing in java with a keen interest in problem-solving. Although I was away from the academic environment, I’ve always kept the fire alive in my heart by solving math-related problems and reading about various subjects, so I decided to continue my education and currently in the last year of my major in AI at the Sharif University of Technology."
  descripe_l2_person: "I'm always open for new ideas so don't hesitate to contact me"
  skills:
    - name: Back End
      percentage: 90
    - name: Dev-Ops
      percentage: 70
    - name: Front End
      percentage: 60
    - name: Machine Learnings
      percentage: 70

  # Experience
  disable_experience: false
  experience:
    - company: "Tapsell"
      role: "Software developer"
      startdate: Apr 2021
      enddate: present
      featuredpoints:
        - point:  Tapsell is an ad network based in Iran. I'm a senior developer in Tapsell's brain team. Our primary duty is to develop an effective method for betting on Ads and Ad places to maximize our profit and our client's profit.
        - point: Technologies that I've worked with here so far includes Kotlin, Spring Framework, Docker, Kubernetes, Kafka, Redis, MongoDB, Prometheus)
    - company: "Royalty"
      role: "Fullstack developer"
      startdate: Sep 2020
      enddate: Apr 2021
      featuredpoints:
        - point: A Java based application for listing properties in Canada.
        - point: Technology stack includes Java, Spring Framework, Docker, MySQL, React JS
    - company: "Amoot"
      role: "Fullstack developer"
      startdate: Jun 2019
      enddate: Dec 2019
      featuredpoints:
        - point: At Amoot, we are maintained and developed new features for National Organization for Civil Registration software like NCR.ir and 3s, a National Card Registration back office.
    - company: "Freelancer"
      role: "Fullstack developer"
      startdate: Apr 2018
      enddate: Jun 2019
      featuredpoints:
        - point: Work on multiple projects like Movic. It was a video streaming service. The best thing about that was I come to work a little with Reactjs, and after several years it was a good experience with UI.
        - point: Technology stack includes Java, Spring Framework, Python, Docker, React JS, Kafka, Postgres, Bootstrap
    - company: "Magic-Mirror"
      role: "Senior Developer"
      startdate: Nov 2016
      enddate: Apr 2018
      featuredpoints:
        - point: I was in a senior developer position; we mainly developed multimedia solutions.
        - point: Inet a user-generated content website for videos like YouTube. it's Technology stack includes Java, Spring, Spring-boot,Kafka, Elastic Search, Redis, Mustache, Postgres, Kubernetes, Docker, Python, Javascript, Html, CSS, Cloudfoundry uaa.
        - point: Filmnet Box an offline video on demand boxes for railways. Technology stack includes PHP, Html, CSS.
        - point: Maintenance of Filmnet ,Plan, Tvnet and Danapp
        - point: Backend for mobile games like Hitboy with python.
    - company: "Homapay"
      role: "Senior Developer"
      startdate: Oct 2015
      enddate: May 2016
      featuredpoints:
        - point: Homapay was a fintech company, and I worked mainly on Hampay.ir solution.
        - point: Technology stack includes Java, MongoDB, mule, RabbitMQ, OpenAM, Nginx, JMeter, Logstash, Docker, Jenkins, Redis, groovy
    - company: "Asan-Pardakht"
      role: "Senior Developer"
      startdate: Mar 2014
      enddate: Oct 2015
      featuredpoints:
        - point: ITIL compliant help desk support system, It was a system that supports LDAP, and has a ticket management system, and works fine in both JBoss and tomcat. Its technology stack includes Java, Grails, AngularJS, Liferay, PostgreSQL, hibernate, spring, angularjs.
        - point: developed a sms sender’s monitoring system using C#, WPF
        - point: Core banking simulator to test Asan Pardakht’s various applications using Java
        - point: Distributor’s Loyalty System using Java and swing
    - company: "Fanap"
      role: "Developer"
      startdate: Sep 2013
      enddate: Mar 2014
      featuredpoints:
        - point: I was responsible for USSD service maintenance and improvement. Technology stack includes Java, web-services, USSD, hibernate
        - point: Loyalty and XRM. Technology stack includes Java, web-services, hibernate
    - company: "Naji"
      role: "Developer"
      startdate: Jun 2011
      enddate: Feb 2013
      featuredpoints:
        - point: I worked with WebNMS, a framework written in Java, and add extensions to it; the Iranian police department will use the system we developed to manage all the network- related assets used by them. Technology stack includes Java, swing, WebNMS, PostgreSQL
        - point: I wrote a client and server of the system that used wap for handheld devices. Technology stack includes wap, JBoss, Java

  # Education
  disable_education: false
  education:
    - degree: "M.S."
      branch: "Artificial Intelligence"
      university: "Sharif University of Technology"
      startedyear: "2019"
      graduation: "2022"
    - degree: "B.S"
      branch: "Information Technology"
      university: "University of Tehran"
      startedyear: "2007"
      graduation: "2014"

  # Projects
  disable_projects: true
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Mathematics Olympiad
      description: Bronze Badge in Iranian Mathematics Olympiad
      img: /images/bronze.png
    - title: Master Enterance Program
      description: Rank 4 in master entrance compatition among 30000 participants 
      img: /images/konkoor.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "aliamiri68@gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: false

  # Blog
  showdescription: false
  tweet: fasle
