baseURL: "https://github.com/aliamiri"
languageCode: "en-us"
title: "Ali Amiri's Portfolio"
theme: "./.."
relativeURLs: true


googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  description: "Ali Amiri - Senior Software Engineer"

  # home
  disable_home: false
  profile_image: "/images/profile.jpg"
  name: "Ali Amiri"
  profession: "Senior Software Engineer"
  github: "https://github.com/aliamiri"
  linkedin: "https://linkedin.com/in/aliamiriakh"

  useresume: true
  customname: "CV"
  resumelink: "/resume.pdf"

  # About
  disable_about: false
  descripe_l1_person: "I am an enthusiastic, creative programmer with about ten years of programming and management experience, specializing in java with a keen
interest in problem‑solving. Besides programming, I have an excellent background in Mathematics and Algorithms through my years of studying
for the Mathematical Olympiad. I have shown a proven record of managing successful software teams in developing new projects and maintaining
existing ones in the past several years."
  descripe_l2_person: "I am a self-starter and a team player, and I am always looking for new challenges to tackle!"
  skills:
    - name: Back End
      percentage: 90
    - name: Dev-Ops
      percentage: 70
    - name: Front End
      percentage: 60
    - name: Machine Learnings
      percentage: 70

  # Experience
  disable_experience: false
  experience:
    - company: "Tapsell"
      role: "Team Lead"
      startdate: Apr 2021
      enddate: present
      featuredpoints:
        - point:  As an ad network, we are developing effective methods for bidding on Ads and Ad places to maximize our profit and our client’s profit. My most significant achievement was handling a stream of billions of records per day using Kafka and Hadoop.
        - point: Kotlin, Java, Spring Framework, Docker, Kubernetes, Kafka, Redis, MongoDB, Prometheus, Grafana, Hadoop, Hudi.
    - company: "Royalty"
      role: "Chief Technology Officer"
      startdate: Jun 2020
      enddate: Apr 2021
      featuredpoints:
        - point: I was responsible for the entire software lifecycle, meetings with clients and business analysis, reading through property laws in Canada, refining the business analysis, designing scalable software architecture, and managing a team of five developers to implement it, finally creating a pipeline for tests and deployment.
        - point: Java, Spring Framework, Docker, MySQL, React JS,Google Cloud Platform, Kafka, Redis.
#    - company: "Amoot"
#      role: "Fullstack developer"
#      startdate: Jun 2019
#      enddate: Dec 2019
#      featuredpoints:
#        - point: At Amoot, we are maintained and developed new features for National Organization for Civil Registration software like NCR.ir and 3s, a National Card Registration back office.
    - company: "Freelancer - Movic"
      role: "Team Lead"
      startdate: Apr 2018
      enddate: Jun 2019
      featuredpoints:
        - point: I have designed the architecture for a video streaming service and managed a team of six developers to implement the service.
        - point: Java, Spring Framework, Python, Docker, React JS,Kafka, Postgres, Bootstrap
    - company: "Magic-Mirror"
      role: "Senior Software Engineer"
      startdate: Nov 2016
      enddate: Apr 2018
      featuredpoints:
        - point: We designed and implemented multiple multimedia streaming solutions. We developed the core systems using Kafka, Redis, and the spring framework.
        - point: Java, Spring, Kafka, Redis, Mustache, Postgres,Docker, Python, JavaScript, Cloud foundry uaa, PHP
    - company: "Homapay"
      role: "Senior Software Engineer"
      startdate: Oct 2015
      enddate: Mar 2016
      featuredpoints:
        - point: In this fintech startup, I worked on micro‑payment architectural design and implementation. The system was an Enterprise Service Bus powered by Mule. I also designed the CI/CD pipelines using Jenkins and wrote the integration tests using Jmeter and groovy.
        - point: Java, Spring, MongoDB, mule, RabbitMQ, Open AM,
  Nginx, JMeter, Logstash, Docker, Jenkins, Redis,
  groovy
    - company: "Asan-Pardakht"
      role: "Software Engineer"
      startdate: Mar 2014
      enddate: Oct 2015
      featuredpoints:
        - point: I worked on ITIL compliant help desk, Core banking simulator, Distributor’s Loyalty System, etc.
        - point: Java, Grails, AngularJS, PostgreSQL, C#, WPF.
    - company: "Fanap"
      role: "Developer"
      startdate: Sep 2013
      enddate: Mar 2014
      featuredpoints:
        - point: USSD service maintenance and improvement. developing the XRM system.
        - point: Java, web‑services, USSD, hibernate
    - company: "Naji"
      role: "Developer"
      startdate: Jun 2011
      enddate: Feb 2013
      featuredpoints:
        - point: I have added several extensions to WebNMS, and I have developed the client and server for a WAP.
        - point: Java, swing, WebNMS, PostgreSQL, wap, JBoss.

  # Education
  disable_education: false
  education:
    - degree: "M.S."
      branch: "Artificial Intelligence"
      university: "Sharif University of Technology"
      startedyear: "2019"
      graduation: "2022"
    - degree: "B.S"
      branch: "Information Technology"
      university: "University of Tehran"
      startedyear: "2007"
      graduation: "2014"

  # Projects
  disable_projects: true
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Mathematics Olympiad
      description: Bronze Badge in Iranian Mathematics Olympiad
      img: /images/bronze.png
    - title: Master Enterance Program
      description: Rank 4 in master entrance compatition among 30000 participants
      img: /images/konkoor.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "aliamiri68 [at] gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: false

  # Blog
  showdescription: false
  tweet: fasle
